#spring:
#  jmx:
#    enabled: false
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:/Users/jokelin/work/estsh/project/edi/i3plus-mes-edi/myDb.db
#    username:
#    password:
#  jpa:
#    database-platform: cn.estsh.i3plus.config.SQLiteDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#spring:
#  datasource:
#    url: jdbc:sqlserver://10.232.38.21:1433;DatabaseName=impp_i3_mes;
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: Test123!
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 10000
#      maximum-pool-size: 10
#      minimum-idle: 1
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  thymeleaf:
#    cache: false
#  jmx:
#    enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vegetables?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sasa
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 1
  thymeleaf:
    cache: false
  jmx:
    enabled: false

mybatis:
  mapper-locations: classpath:cn.dominic.mapper/*Mapper.xml
  type-aliases-package: cn.dominic.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper: info

javafx:
  stage:
    resizable: false
  title: 蔬菜管理系统